/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/** Stream info returned by the portal picker. */
export interface PortalStream {
  nodeId: number
  sourceType: number
  width: number
  height: number
}
/** Result from the portal picker — streams + PipeWire remote fd. */
export interface PickerResult {
  streams: Array<PortalStream>
  pipewireFd: number
}
/** Audio samples (interleaved f32 PCM). */
export interface AudioChunk {
  channels: number
  sampleRate: number
  data: Buffer
}
/** Shared memory info returned by startCapture. */
export interface ShmInfo {
  shmPath: string
  shmSize: number
  headerSize: number
}
/** Capture options. */
export interface CaptureOptions {
  nodeId: number
  pipewireFd: number
  fps: number
  audio: boolean
  excludePid?: number
}
export declare function showPicker(sourceTypes: number): Promise<PickerResult | null>
/**
 * Start capturing. Returns a Buffer backed by the shared memory region.
 * The renderer can read frames directly from this buffer — zero copy.
 *
 * Layout: ShmHeader (32 bytes) + slot0 + slot1
 * ShmHeader: { seq: u64, width: u32, height: u32, stride: u32, data_offset: u32, data_size: u32 }
 * Poll seq to detect new frames, read pixels from data_offset..data_offset+data_size.
 * Start capturing. Returns a handle object with shm info.
 * Call `getShmBuffer()` to get a zero-copy view into the shared memory.
 */
export declare function startCapture(options: CaptureOptions): ShmInfo
/** Read accumulated audio samples. Returns null if not available. */
export declare function readAudio(): AudioChunk | null
/**
 * Read the current frame header from shared memory. Returns [seq, width, height, dataOffset, dataSize].
 * The renderer uses this to know where to read pixels from the mmap'd buffer.
 * Returns null if not capturing or no frame available.
 */
export declare function readFrameInfo(): Array<number> | null
/**
 * Read frame pixels from shared memory. Zero-copy — returns a Buffer view into mmap'd memory.
 * `offset` and `size` come from readFrameInfo().
 */
export declare function readFramePixels(offset: number, size: number): Buffer
/** Check if capture is currently active. */
export declare function isCapturing(): boolean
/** Stop all capture (video + audio) and release resources. */
export declare function stopCapture(): void
