/* eslint-disable */
/* auto-generated by napi-rs */

const { existsSync, readFileSync } = require('fs')
const { join } = require('path')

const { platform, arch } = process

let nativeBinding = null
let localFileExisted = false
let loadError = null

function isMusl() {
  if (!process.report || typeof process.report.getReport !== 'function') {
    try {
      const lddPath = require('child_process').execSync('which ldd').toString().trim()
      return readFileSync(lddPath, 'utf8').includes('musl')
    } catch {
      return true
    }
  } else {
    const report = process.report.getReport()
    const glibcVersionRuntime = typeof report === 'string'
      ? JSON.parse(report)?.header?.glibcVersionRuntime
      : report?.header?.glibcVersionRuntime
    return !glibcVersionRuntime
  }
}

switch (platform) {
  case 'linux':
    switch (arch) {
      case 'x64':
        localFileExisted = existsSync(join(__dirname, 'pipecap.linux-x64-gnu.node'))
        try {
          if (localFileExisted) {
            nativeBinding = require('./pipecap.linux-x64-gnu.node')
          } else {
            nativeBinding = require('@librecord/pipecap-linux-x64-gnu')
          }
        } catch (e) {
          loadError = e
        }
        break
      case 'arm64':
        localFileExisted = existsSync(join(__dirname, 'pipecap.linux-arm64-gnu.node'))
        try {
          if (localFileExisted) {
            nativeBinding = require('./pipecap.linux-arm64-gnu.node')
          } else {
            nativeBinding = require('@librecord/pipecap-linux-arm64-gnu')
          }
        } catch (e) {
          loadError = e
        }
        break
      default:
        throw new Error(`Unsupported architecture on Linux: ${arch}`)
    }
    break
  default:
    throw new Error(`Unsupported OS: ${platform}, pipecap only supports Linux`)
}

if (!nativeBinding) {
  if (loadError) {
    throw loadError
  }
  throw new Error('Failed to load native binding')
}

const { showPicker, startCapture, readFrame, stopCapture, startAudioCapture, readAudio, stopAudioCapture } = nativeBinding

module.exports.showPicker = showPicker
module.exports.startCapture = startCapture
module.exports.readFrame = readFrame
module.exports.stopCapture = stopCapture
module.exports.startAudioCapture = startAudioCapture
module.exports.readAudio = readAudio
module.exports.stopAudioCapture = stopAudioCapture
