/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/** Stream info returned by the portal picker. */
export interface PortalStream {
  nodeId: number
  /** 1=monitor, 2=window */
  sourceType: number
  width: number
  height: number
}
/** Result from the portal picker. */
export interface PickerResult {
  streams: Array<PortalStream>
  /** PipeWire remote fd — pass to startCapture. */
  pipewireFd: number
}
/** Capture options. */
export interface CaptureOptions {
  /** PipeWire node ID from showPicker(). */
  nodeId: number
  /** PipeWire remote fd from showPicker(). */
  pipewireFd: number
  /** Requested frame rate (0 = source native rate). */
  fps: number
  /** Enable audio capture. */
  audio: boolean
  /**
   * For per-app audio: the application name to capture (from listAudioApps).
   * If unset or empty, captures all system audio.
   */
  appName?: string
}
/** Shared memory info returned by startCapture. */
export interface ShmInfo {
  /** Path to the shared memory file. */
  shmPath: string
  /** Total size of the shared memory region in bytes. */
  shmSize: number
  /** Size of the header at the start of the region. */
  headerSize: number
}
/** An audio-producing application detected in PipeWire. */
export interface AudioApp {
  /** Display name of the application. */
  name: string
}
/** Audio samples (interleaved f32 PCM as little-endian bytes). */
export interface AudioChunk {
  channels: number
  sampleRate: number
  data: Buffer
}
/**
 * Show the native xdg-desktop-portal screen/window picker.
 * `sourceTypes`: 1=monitors, 2=windows, 3=both.
 * Returns the selected stream(s), or null if the user cancelled.
 */
export declare function showPicker(sourceTypes: number): Promise<PickerResult | null>
/**
 * List applications currently producing audio.
 * Returns unique app names — show these in a dropdown for per-app audio selection.
 */
export declare function listAudioApps(): Array<AudioApp>
/**
 * Start video + optional audio capture.
 *
 * Video frames are written to shared memory at `/dev/shm/pipecap-frames`.
 * Read the 32-byte header to detect new frames, then read pixel data.
 *
 * Audio mode depends on `appName`:
 * - `undefined` or `""` → capture all system audio (sink monitor)
 * - `"Firefox"` etc → capture only that app's audio (PipeWire link-based)
 *
 * Returns shared memory info for the renderer.
 */
export declare function startCapture(options: CaptureOptions): ShmInfo
/**
 * Read accumulated audio samples. Returns null if no audio available.
 * Audio is interleaved f32 PCM (typically stereo 48kHz). Buffer is drained on each call.
 */
export declare function readAudio(): AudioChunk | null
/** Check if capture is currently active. */
export declare function isCapturing(): boolean
/** Stop all capture (video + audio) and release resources. */
export declare function stopCapture(): void
