/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/** Stream info returned by the portal picker. */
export interface PortalStream {
  nodeId: number
  sourceType: number
  width: number
  height: number
}
/** A single video frame (RGBA pixels). */
export interface Frame {
  width: number
  height: number
  data: Buffer
}
/** Audio samples (interleaved f32 PCM). */
export interface AudioChunk {
  channels: number
  sampleRate: number
  /** Interleaved f32 PCM samples as little-endian bytes. */
  data: Buffer
}
/**
 * Show the native xdg-desktop-portal screen/window picker.
 * `source_types`: 1=monitors, 2=windows, 3=both.
 * Returns the selected stream(s), or null if the user cancelled.
 * Result from the portal picker — streams + PipeWire remote fd.
 */
export interface PickerResult {
  streams: Array<PortalStream>
  /** Raw fd to the PipeWire remote. Pass this to startCapture. */
  pipewireFd: number
}
export declare function showPicker(sourceTypes: number): Promise<PickerResult | null>
/** Capture options. */
export interface CaptureOptions {
  nodeId: number
  /** PipeWire remote fd from showPicker(). */
  pipewireFd: number
  fps: number
  audio: boolean
  /** PID of the current process — used to exclude own audio output from capture. */
  excludePid?: number
}
/**
 * Start capturing from a PipeWire node.
 * `node_id` must come from show_picker() (portal-consented).
 */
export declare function startCapture(options: CaptureOptions): void
/** Read the latest video frame. Returns null if no frame is available yet. */
export declare function readFrame(): Frame | null
/**
 * Read accumulated audio samples. Returns null if no audio available or audio not enabled.
 * Audio is interleaved f32 PCM (typically stereo 48kHz). Buffer is drained on each call.
 */
export declare function readAudio(): AudioChunk | null
/** Check if capture is currently active. */
export declare function isCapturing(): boolean
/** Stop all capture (video + audio) and release PipeWire resources. */
export declare function stopCapture(): void
